In [1]:
print("a")

a

In [2]:
print("hello")

hello

In [3]:
import pandas as pd

In [4]:
df =pd.read_csv("data_analysis_project/Hr_Employe_Attrition.csv")
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [5]:
df.info

<bound method DataFrame.info of       Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
4                    2          1        Medical              1
...                ...        ...            ...            ...
1465                23          2        Medical              1
1466                 6          1        Medical              1
1467                 4          3  Life Sciences              1
1468                 2          3        Medical              1
1469                 8          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
1                  2  ...                         4            80
2                  4  ...                         2            80
3                  5  ...                         3            80
4                  7  ...                         4            80
...              ...  ...                       ...           ...
1465            2061  ...                         3            80
1466            2062  ...                         1            80
1467            2064  ...                         2            80
1468            2065  ...                         4            80
1469            2068  ...                         1            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
1                    1                 10                      3
2                    0                  7                      3
3                    0                  8                      3
4                    1                  6                      3
...                ...                ...                    ...
1465                 1                 17                      3
1466                 1                  9                      5
1467                 1                  6                      0
1468                 0                 17                      3
1469                 0                  6                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
1                  3              10                  7
2                  3               0                  0
3                  3               8                  7
4                  3               2                  2
...              ...             ...                ...
1465               3               5                  2
1466               3               7                  7
1467               3               6                  2
1468               2               9                  6
1469               4               4                  3

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
1                           1                     7
2                           0                     0
3                           3                     0
4                           2                     2
...                       ...                   ...
1465                        0                     3
1466                        1                     7
1467                        0                     3
1468                        0                     8
1469                        1                     2

[1470 rows x 35 columns]>

In [6]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [7]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [12]:
# Total employees kitne hain?
totalemployees =df["EmployeeNumber"].count();
totalemployees

np.int64(1470)

In [19]:
# Company me male aur female employees kitne hain?
gender =df.groupby("Gender")["EmployeeNumber"].count();
gender

Gender
Female    588
Male      882
Name: EmployeeNumber, dtype: int64

In [20]:
# Har Department me kitne employees hain?
Department =df.groupby("Department")["EmployeeNumber"].count();
Department

Department
Human Resources            63
Research & Development    961
Sales                     446
Name: EmployeeNumber, dtype: int64

In [21]:
# Company ki average MonthlyIncome kya hai?
average =df["MonthlyIncome"].mean();
average

np.float64(6502.931292517007)

In [22]:
# Department-wise average salary calculate karo.
Department =df.groupby("Department")["EmployeeNumber"].mean();
Department

Department
Human Resources           1205.269841
Research & Development    1006.503642
Sales                     1038.946188
Name: EmployeeNumber, dtype: float64

In [23]:
attrition_yes = df[df["Attrition"] == "Yes"];
attrition_yes

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [27]:
 Attrition = df["Attrition"].value_counts();
 Attrition

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [29]:
# Department-wise Attrition count nikalo.
Department_Attr =df.groupby("Department")["Attrition"].value_counts();
Department_Attr

Department              Attrition
Human Resources         No            51
                        Yes           12
Research & Development  No           828
                        Yes          133
Sales                   No           354
                        Yes           92
Name: count, dtype: int64

In [34]:
# OverTime = Yes aur Attrition = Yes wale employees kitne hain?
Department_Attr =df.groupby(["Attrition ="yes"])["EmployeeNumber"].counts();
Department_Attr

Department
Research & Development    133
Sales                      92
Human Resources            12
Name: count, dtype: int64

In [38]:
# Jin employees ki YearsAtCompany > 5 hai, unki average MonthlyIncome nikalo.
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [41]:
# Jin employees ki YearsAtCompany > 5 hai, unki average MonthlyIncome nikalo.
result2 = df[df["YearsAtCompany"] > 5]["MonthlyIncome"].mean()
result2

np.float64(8098.491354466859)

In [45]:
# Department-wise Attrition Rate (%) calculate karo.
attrition_rate = (
    df.groupby("Department")["Attrition"]
      .apply(lambda x: round((x == "Yes").sum() / len(x) * 100, 2))
)
attrition_rate

Department
Human Resources           19.05
Research & Development    13.84
Sales                     20.63
Name: Attrition, dtype: float64

In [47]:
# OverTime = Yes aur Attrition = Yes wale employees kitne hain?
result1 = df[
    (df["OverTime"] == "Yes") &
    (df["Attrition"] == "Yes")
].shape[0]
result1

127

In [50]:
# Department-wise average MonthlyIncome nikalo.
Department_wise_average = df.groupby("Department")["MonthlyIncome"].count()
Department_wise_average

Department
Human Resources            63
Research & Development    961
Sales                     446
Name: MonthlyIncome, dtype: int64

In [51]:
# JobRole-wise employee count nikalo.
JobRole_wise_average = df.groupby("JobRole")["EmployeeNumber"].count()
JobRole_wise_average

JobRole
Healthcare Representative    131
Human Resources               52
Laboratory Technician        259
Manager                      102
Manufacturing Director       145
Research Director             80
Research Scientist           292
Sales Executive              326
Sales Representative          83
Name: EmployeeNumber, dtype: int64

In [52]:
# JobRole-wise average MonthlyIncome nikalo.
JobRole_wise_average = df.groupby("JobRole")["MonthlyIncome"].mean()
JobRole_wise_average

JobRole
Healthcare Representative     7528.763359
Human Resources               4235.750000
Laboratory Technician         3237.169884
Manager                      17181.676471
Manufacturing Director        7295.137931
Research Director            16033.550000
Research Scientist            3239.972603
Sales Executive               6924.279141
Sales Representative          2626.000000
Name: MonthlyIncome, dtype: float64

In [53]:
# Gender-wise Attrition count nikalo.
Gender_wise_Attrition = df.groupby("Gender")["Attrition"].count()
Gender_wise_Attrition

Gender
Female    588
Male      882
Name: Attrition, dtype: int64

In [1]:
print("hello")

hello

In [2]:
import mysql.connector

print("MySQL Connector OK")

MySQL Connector OK

In [5]:
from sqlalchemy import create_engine
import pandas as pd
import pymysql

USER = "root"
PASSWORD = "shivam@1734"
HOST = "localhost"
PORT = "3306"
DATABASE = "hr_analysis"
TABLE_NAME = "Hrtable"

# 2. Read the local CSV file into a Pandas DataFrame
# file_path = "Hr_Employe_Attrition.csv"
# df = pd.read_csv("Hr_Employe_Attrition.csv")

# 3. Create the SQLAlchemy connection engine
# Format: mysql+pymysql://user:password@host:port/database
engine = create_engine(f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

In [6]:
import pymysql

print("PyMySQL OK")

PyMySQL OK

In [8]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:shivam@1734@localhost/hr_analysis"
)

print("Connection setup OK")

Connection setup OK

In [16]:
from sqlalchemy import create_engine
import pandas as pd
import pymysql

USER = "root"
PASSWORD = "shivam@1734"
HOST = "localhost"
PORT = "3306"
DATABASE = "hr_analysis"
TABLE_NAME = "Hrtable"

# 2. Read the local CSV file into a Pandas DataFrame
# file_path = "Hr_Employe_Attrition.csv"
# df = pd.read_csv("Hr_Employe_Attrition.csv")

# 3. Create the SQLAlchemy connection engine
# Format: mysql+pymysql://user:password@host:port/database
engine = create_engine(
    "mysql+pymysql://root:shivam@1734@localhost/hr_analysis"
)
print("Connection setup OK")

Connection setup OK

In [18]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# 1. CSV dataset
df =pd.read_csv("data_analysis_project/Hr_Employe_Attrition.csv")


# 2. MySQL connection
connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="shivam@1734",
    host="localhost",
    port=3306,
    database="hr_analysis"
)

engine = create_engine(connection_url)

print("MySQL connected successfully")

# 3. Upload Python DataFrame → MySQL table
df.to_sql(
    name="Hrtable",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset uploaded successfully")

# 4. Read table back from MySQL
df_sql = pd.read_sql("SELECT * FROM Hrtable", engine)

df_sql.head()

MySQL connected successfully

C:\Users\DELL\AppData\Local\Temp\ipykernel_1720\2298003610.py:24: UserWarning: The provided table name 'Hrtable' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(

Dataset uploaded successfully

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2